# Generated by Django 4.0.3 on 2022-03-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_anonymoususer_id_alter_anonymoususer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymoususer',
            name='username',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
