# Generated by Django 4.0.3 on 2022-03-20 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_anonymoususer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='to_anon_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notf_to_anon_user', to='base.anonymoususer'),
        ),
    ]
