# Generated by Django 4.0.3 on 2022-03-20 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_notification_to_anon_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='anonymous_user',
            new_name='anon_user',
        ),
    ]
