# Generated by Django 4.0.2 on 2022-03-01 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_article_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notf_like_article',
        ),
        migrations.AddField(
            model_name='article',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_article', to='base.article'),
        ),
        migrations.DeleteModel(
            name='LikeArticle',
        ),
    ]
