# Generated by Django 4.0.2 on 2022-03-07 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_follower_follower_follower_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='anonymous_user',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_post_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
