# Generated by Django 4.0.3 on 2022-03-21 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_post_video_alter_post_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('anon_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_messagess_anon_user', to='base.anonymoususer')),
                ('articles', models.ManyToManyField(related_name='saved_messages_article', to='base.post')),
                ('posts', models.ManyToManyField(related_name='saved_message_post', to='base.post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_messages_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_reason', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('clients', models.ManyToManyField(related_name='appointment_client', to='base.anonymoususer')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
