# Generated by Django 4.0.3 on 2022-03-23 06:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_anonymoususer_anonuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctors',
            field=models.ManyToManyField(related_name='appointment_doctors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='clients',
            field=models.ManyToManyField(related_name='appointment_clients', to='base.anonuser'),
        ),
    ]
