# Generated by Django 4.0.3 on 2022-03-23 10:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_appointment_reason_appointment_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='clients',
            field=models.ManyToManyField(related_name='appointment_client', to='base.anonuser'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctors',
            field=models.ManyToManyField(related_name='appointment_doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
