# Generated by Django 4.0.3 on 2022-03-23 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_appointment_doctors_remove_appointment_reason_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
    ]
