# Generated by Django 4.0.3 on 2022-03-24 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_rename_clients_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='from_anon_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notf_from_anon_user', to='base.anonuser'),
        ),
    ]
