# Generated by Django 4.0.3 on 2022-03-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_commentarticle_anon_user_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonuser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
