# Generated by Django 4.0.3 on 2022-05-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_user_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to='base.like'),
        ),
    ]
