# Generated by Django 4.0 on 2022-07-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0021_appointment_checked_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='article_likes', to='base.Like'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='messages',
            field=models.ManyToManyField(related_name='messages', to='base.ChatMessage'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.ManyToManyField(related_name='child_comment', to='base.ChildComment'),
        ),
        migrations.AlterField(
            model_name='commentarticle',
            name='comment',
            field=models.ManyToManyField(related_name='child_comment_article', to='base.ChildCommentArticle'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to='base.Like'),
        ),
        migrations.AlterField(
            model_name='savedmessages',
            name='articles',
            field=models.ManyToManyField(related_name='saved_messages_article', to='base.Article'),
        ),
        migrations.AlterField(
            model_name='savedmessages',
            name='posts',
            field=models.ManyToManyField(related_name='saved_message_post', to='base.Post'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
